### ISSUE TITLE
How use this?

### ISSUE THREAD

**Issue by Dazmed707** [robtimus/obfuscation-yaml#1]
Need obfusca code .yaml a phishlet for evilginx ? 

how to use this tool?

check this. for example

https://github.com/thecityofhereafter/google.yaml/blob/master/google.yaml

**Comment by robtimus** [comment]
This is a library to provide one-way obfuscation of YAML.  Once obfuscated, the original text cannot be retrieved anymore. It's mostly meant to be used for logging, or for other purposes where some of the contents of YAML files should no longer be visible.

As I don't see anything in your example that looks like it would benefit from this library (like passwords or personal data), I'm not sure the type of obfuscation it provides is for you. I have a feeling you want something that's not one-way instead.

**Comment by Dazmed707** [comment]
https://github.com/thecityofhereafter/google.yaml/blob/master/google.yaml

Estos .yaml son configuraciones avanzadas para un programa de proxy, necesito ofuscar para que no puedan robar mi trabajo. ¿sirve tu herramienta para esto?
